# Generated by Django 5.0 on 2026-02-28 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Artificial Intelligence')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this category covers",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when category was created",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the news source", max_length=200
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="RSS feed URL or API endpoint", unique=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS Feed"),
                            ("api", "API"),
                            ("manual", "Manual Entry"),
                        ],
                        default="rss",
                        help_text="Type of source",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the news source"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to fetch articles from this source",
                    ),
                ),
                (
                    "fetch_interval",
                    models.IntegerField(
                        default=60, help_text="Fetch interval in minutes"
                    ),
                ),
                (
                    "last_fetched",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful fetch",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when source was added"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Article headline", max_length=500),
                ),
                ("content", models.TextField(help_text="Full article content")),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Short summary or excerpt"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Original article URL (must be unique)",
                        max_length=1000,
                        unique=True,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="Article author name", max_length=200
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Featured image URL", max_length=1000
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Original publication date",
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when article was fetched",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, help_text="Number of times article was viewed"
                    ),
                ),
                (
                    "bookmark_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of users who bookmarked this article",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Article category (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="articles.category",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="RSS source this article came from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="articles.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="articles_ar_publish_c1a2fc_idx"
                    ),
                    models.Index(
                        fields=["category"], name="articles_ar_categor_ef2274_idx"
                    ),
                    models.Index(
                        fields=["source"], name="articles_ar_source__44296e_idx"
                    ),
                ],
            },
        ),
    ]
