# Generated by Django 5.0 on 2026-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_source_last_fetch_error_source_last_fetch_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='description',
        ),
        migrations.RemoveField(
            model_name='source',
            name='fetch_interval',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_fetch_error',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_fetch_status',
        ),
        migrations.RemoveField(
            model_name='source',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='total_articles_fetched',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='fetch_frequency',
            field=models.IntegerField(default=60, help_text='How often to fetch (in minutes)'),
        ),
        migrations.AddField(
            model_name='source',
            name='rss_feed_url',
            field=models.URLField(blank=True, help_text='RSS feed URL for automatic article fetching', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='website_url',
            field=models.URLField(default='https://example.com', help_text='Main website URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='last_fetched',
            field=models.DateTimeField(blank=True, help_text='Last time articles were fetched from this source', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='Source name (e.g., TechCrunch, The Verge)', max_length=100, unique=True),
        ),
    ]
