# Generated by Django 5.0 on 2026-02-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when article was opened"
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        default=0, help_text="Time spent reading in seconds"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reading histories",
                "ordering": ["-read_at"],
            },
        ),
        migrations.CreateModel(
            name="UserArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user marked this article as read",
                    ),
                ),
                (
                    "is_bookmarked",
                    models.BooleanField(
                        default=False, help_text="Whether user bookmarked this article"
                    ),
                ),
                (
                    "is_saved_for_later",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user saved this article for later reading",
                    ),
                ),
                (
                    "keep_decision",
                    models.CharField(
                        choices=[
                            ("undecided", "Undecided"),
                            ("keep", "Keep"),
                            ("delete", "Delete"),
                        ],
                        default="undecided",
                        help_text="User's decision to keep or delete this article",
                        max_length=10,
                    ),
                ),
                (
                    "bookmarked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when article was bookmarked",
                        null=True,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when article was marked as read",
                        null=True,
                    ),
                ),
                (
                    "saved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when article was saved for later",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when interaction was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when interaction was last updated",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when reference was created",
                    ),
                ),
                (
                    "referenced_article",
                    models.ForeignKey(
                        help_text="Article being referenced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenced_in_notes",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Note content")),
                (
                    "has_follow_up",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this note requires follow-up action",
                    ),
                ),
                (
                    "follow_up_done",
                    models.BooleanField(
                        default=False,
                        help_text="Whether follow-up action has been completed",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional deadline for follow-up action",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when note was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp when note was last updated"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Article this note is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
